root = "."
tmp_dir = "tmp"

[build]
  cmd = "go build -o ./tmp/main ./cmd/server"
  bin = "./tmp/main"
  include_ext = ["go", "mod"]
  exclude_dir = ["tmp", "db", "dist"]
  exclude_file = ["README.md"]
  delay = 1000

[log]
  time = true

[misc]
  clean_on_exit = true
